language: haskell
ghc:
    - 7.6
    - 7.8
env:
    - AWSBOUND=1
    - AWSBOUND=2
install:
    - cabal install --only-dependencies --enable-tests --constraint="aws<$AWSBOUND"
script:
    - cabal configure --enable-tests && cabal build
